server:
  port: 80 # 服务端口

spring:
  application:
    name: gateway # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.20:8848 # nacos服务地址
    gateway:
      discovery:
        locator:
          enabled: true # gateway可以发现nacos中的微服务，并自动生成转发路由
      routes:
        - id: core
          uri: lb://core
          predicates:
            - Path=/*/core/**
        - id: sms
          uri: lb://sms
          predicates:
            - Path=/*/sms/**
        - id: oss
          uri: lb://oss
          predicates:
            - Path=/*/oss/**

