server:
  port: 8130 # 服务端口

spring:
  application:
    name: oss # 服务名
    #spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.80.141:8848 # nacos服务地址
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    keyId: LTAI5tNWST9aTHbkjSLXV5EN
    keySecret: CetBJi0Av4HlJd9KjqjRrE0gcdJ5bW
    bucketName: liubusi-packagehub
